services:
  tekkom-bot:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app

  tekkom-bot-api:
    container_name: tekkom-bot-api 
    image: tekkom-bot-api
    restart: always
    build:
      context: ./api
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    env_file:
      .env

  postgres:
    image: postgres:15
    container_name: tekkom-bot_database
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-tekkom-bot}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB:-tekkom-bot}
      TZ: Europe/Oslo
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tekkom-bot -d tekkom-bot"]
      interval: 5s
      retries: 5

volumes:
  postgres_data:
