services:
  tekkom_bot:
    container_name: tekkom_bot
    image: tekkom_bot
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      - tekkom_bot_api

  tekkom_bot_api:
    container_name: tekkom_bot_api 
    image: tekkom_bot_api
    restart: always
    build:
      context: ./api
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    env_file:
      .env

  postgres:
    image: postgres:18
    container_name: tekkom_bot_database
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-tekkom-bot}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB:-tekkom-bot}
      TZ: Europe/Oslo
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tekkom-bot -d tekkom-bot"]
      interval: 5s
      retries: 5

volumes:
  postgres_data:
